AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Manager API - Spring Boot + DynamoDB

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  TaskManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kishore.taskmanager.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
          AWS_REGION: !Ref AWS::Region
          SPRING_PROFILES_ACTIVE: cloud
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tasks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
