AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Manager API - Spring Boot + DynamoDB

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  TaskManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kishore.taskmanager.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
