name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Start LocalStack with Docker socket
        run: |
          docker run -d --name localstack \
            -p 4566:4566 \
            -e SERVICES=dynamodb \
            -v /var/run/docker.sock:/var/run/docker.sock \
            localstack/localstack:latest

      - name: Wait for LocalStack to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:4566/health | grep '"dynamodb": "running"' && break
            echo "Waiting for LocalStack..."
            sleep 5
          done

      # - name: Build and run tests
      #   run: mvn clean install -Dspring.profiles.active=test

      - name: Run tests with cloud profile
        run: mvn test -Dspring.profiles.active=cloud -DAWS_REGION=${{ vars.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          sam deploy \
            --stack-name task-manager-api \
            --region $AWS_REGION \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
